import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const publicDir = path.join(root, 'public');
const distDir = path.join(root, 'dist');
const generatedPath = path.join(root, 'src/render/assets/manifest.generated.ts');

const MEDIA_ROOTS = ['models', 'textures', 'env', 'vfx'];
const HASH_LEN = 12;

function walk(dir) {
  const out = [];
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) out.push(...walk(p));
    else if (ent.isFile()) out.push(p);
  }
  return out;
}

function mediaFiles() {
  const files = [];
  for (const rootName of MEDIA_ROOTS) {
    const dir = path.join(publicDir, rootName);
    if (existsSync(dir)) files.push(...walk(dir));
  }
  return files.sort();
}

function manifestEntries() {
  const entries = {};
  for (const file of mediaFiles()) {
    const rel = path.relative(publicDir, file).split(path.sep).join('/');
    const parsed = path.posix.parse(rel);
    const hash = createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, HASH_LEN);
    const hashed = path.posix.join('/media', parsed.dir, `${parsed.name}.${hash}${parsed.ext}`);
    entries[rel] = hashed;
  }
  return entries;
}

function generate() {
  const entries = manifestEntries();
  mkdirSync(path.dirname(generatedPath), { recursive: true });
  writeFileSync(
    generatedPath,
    [
      '// Generated by scripts/build_media_manifest.mjs. Do not edit by hand.',
      'export const MEDIA_ASSETS: Record<string, string> = ',
      `${JSON.stringify(entries, null, 2)} as const;`,
      '',
    ].join('\n'),
  );
  console.log(`generated ${path.relative(root, generatedPath)} (${Object.keys(entries).length} media assets)`);
}

function emit() {
  const entries = manifestEntries();
  const mediaDir = path.join(distDir, 'media');
  rmSync(mediaDir, { recursive: true, force: true });
  for (const [logical, url] of Object.entries(entries)) {
    const src = path.join(publicDir, logical);
    const dest = path.join(distDir, url.replace(/^\//, ''));
    mkdirSync(path.dirname(dest), { recursive: true });
    copyFileSync(src, dest);
  }
  console.log(`emitted ${Object.keys(entries).length} hashed media assets to ${path.relative(root, mediaDir)}`);
}

const cmd = process.argv[2] ?? 'generate';
if (cmd === 'generate') generate();
else if (cmd === 'emit') emit();
else {
  console.error(`unknown command: ${cmd}`);
  process.exit(1);
}
